//Регистрация нового пользователя
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "testingsignin@mail.ru",
  "password": "qweasdzxc",
  "name": "Первый тестовый пользователь"
  }

####
//Аутентификация пользователя
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "testingsignin@mail.ru",
  "password": "qweasdzxc"
}
###

//Достать собственный профиль
###
GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlYWNhMzE2MjE3ZmJhNWEyOGZjNzkiLCJpYXQiOjE2NTAzNzM4ODAsImV4cCI6MTY1MDk3ODY4MH0.SGM8Fzt_HFV3ccedP3EgQNYq-w-GGIZ44Cw0DhQCm5Q

//Обновить информацию о пользователе
###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlYWNhMzE2MjE3ZmJhNWEyOGZjNzkiLCJpYXQiOjE2NTAzNzM4ODAsImV4cCI6MTY1MDk3ODY4MH0.SGM8Fzt_HFV3ccedP3EgQNYq-w-GGIZ44Cw0DhQCm5Q

{
  "email": "testingsigninl@mail.ru",
  "name": "Первый тестовый пользов"
  }


  //Достать все фильмы
###
GET http://localhost:3000/movies
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlYWNhMzE2MjE3ZmJhNWEyOGZjNzkiLCJpYXQiOjE2NTAzNzM4ODAsImV4cCI6MTY1MDk3ODY4MH0.SGM8Fzt_HFV3ccedP3EgQNYq-w-GGIZ44Cw0DhQCm5Q

//Добавить новый фильм
###
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlYWNhMzE2MjE3ZmJhNWEyOGZjNzkiLCJpYXQiOjE2NTAzNzM4ODAsImV4cCI6MTY1MDk3ODY4MH0.SGM8Fzt_HFV3ccedP3EgQNYq-w-GGIZ44Cw0DhQCm5Q

{
      "country": "Austria",
      "director": "Sir Christopher Li",
      "duration": 138,
      "year": "2020",
      "description": "Here will be a long description",
      "image": "https://someurl.com",
      "trailerLink": "https://someurl.com",
      "thumbnail": "https://someurl.com",
      "movieId": "5",
      "nameRU": "Властелин Колец",
      "nameEN": "Lord of the Rings"
}

//Удалить конкретный фильм
###
DELETE http://localhost:3000/movies/625ed17a1b70f345a2e8416f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjVlYWNhMzE2MjE3ZmJhNWEyOGZjNzkiLCJpYXQiOjE2NTAzNzM4ODAsImV4cCI6MTY1MDk3ODY4MH0.SGM8Fzt_HFV3ccedP3EgQNYq-w-GGIZ44Cw0DhQCm5Q


